pipeline {
    agent any

    stages {
        stage('Compile and Clean') { 
            steps {
                bat 'mvn compile'
            }
        }
       
	    // stage('Junit5 Test') { 
        //    steps {
        //        bat 'mvn test'
        //    }
        // }

        // stage('Jacoco Report') {
        //     steps {
        //         jacoco() 
        //     }
        // }

	    // stage('SonarQube') {
		//     steps {
		// 		bat label: '', script: '''mvn sonar:sonar \
		// 		-Dsonar.host.url=http://CDLVDIVRO1735:9000 \
		// 		-Dsonar.login=squ_a8f15ac76bd736504d5a433bec3bf88be010d477'''
		// 	}
   	    // }
      
        stage('Maven Build') { 
            steps {
                bat 'mvn clean install'
            }
        }
        
        stage('Build Docker image'){
            steps {                       
            	bat 'docker build -t docker.repository.esi.adp.com/clientcentral/training/adp-batch2-2024-team1-eureka --build-arg VER=1.0 .'
		    }
        }
      
        // stage('Docker Login'){
        //     steps {
        //         echo "docker login from console"
        //         bat 'docker login docker.repository.esi.adp.com -u clientcentralcicd -p $DOCKERHUB_CREDENTIALS'
        //     }                
        // }

        stage('Docker Push'){
            steps {
                bat 'docker push docker.repository.esi.adp.com/clientcentral/training/adp-batch2-2024-team1-eureka'
            }
        }
        
        // stage('Docker deploy'){
        //     steps {
        //         bat 'docker run -itd -p  9090:9090 docker.repository.esi.adp.com/clientcentral/training/adp-batch2-2024-team1-eureka'
        //     }
        // }
    }
}