server:
  port: 8761

spring:
  application:
    name: eureka

#By default, the registry also tries to register itself,
#so you need to disable that behavior as well.
eureka:
  client:
    register-with-eureka: false

  # If not disabled,When the registry starts, it will complain (with a stacktrace)
  #that there are no replica nodes to which the registry can connect.
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF